### ISSUE TITLE
Music is not always added to the queue list after adding URL

### ISSUE THREAD

**Issue by colby** [nijotz/shitstream#18]
```
Connected
Received URL
URL appears to be valid
Starting youtube-dl
Downloading song
0.7% of 8.97MiB at 642.56KiB/s ETA 00:14
1.4% of 8.97MiB at  1.17MiB/s ETA 00:07
2.8% of 8.97MiB at  1.99MiB/s ETA 00:04
5.6% of 8.97MiB at  3.30MiB/s ETA 00:02
11.1% of 8.97MiB at  5.41MiB/s ETA 00:01
22.3% of 8.97MiB at  7.42MiB/s ETA 00:00
44.6% of 8.97MiB at  3.54MiB/s ETA 00:01
89.2% of 8.97MiB at  3.03MiB/s ETA 00:00
100.0% of 8.97MiB at  3.00MiB/s ETA 00:00
Download and conversion finished
Adding song to music database
Song added to music database
Adding song to queue
```

vs

```
Connected
Received URL
URL appears to be valid
Starting youtube-dl
Downloading song
0.7% of 8.97MiB at 642.56KiB/s ETA 00:14
1.4% of 8.97MiB at  1.17MiB/s ETA 00:07
2.8% of 8.97MiB at  1.99MiB/s ETA 00:04
5.6% of 8.97MiB at  3.30MiB/s ETA 00:02
11.1% of 8.97MiB at  5.41MiB/s ETA 00:01
22.3% of 8.97MiB at  7.42MiB/s ETA 00:00
44.6% of 8.97MiB at  3.54MiB/s ETA 00:01
89.2% of 8.97MiB at  3.03MiB/s ETA 00:00
100.0% of 8.97MiB at  3.00MiB/s ETA 00:00
Download and conversion finished
Adding song to music database
```

**Comment by colby** [comment]
Bug

**Comment by colby** [comment]
This might have been a backend hiccup.

**Comment by colby** [comment]
Still seeing this issue.

![screen shot 2014-08-27 at 2 40 14 pm](https://cloud.githubusercontent.com/assets/111192/4067877/bfec44be-2e32-11e4-92f8-a96745421ed7.png)

**Comment by nijotz** [comment]
There was a race condition where it would tell MPD to update the database, get the job id, and then check to see what the current job ID was.  But it would ask immediately, before the job got a chance to start, would see that no job was running and assume it was done.  Now it also looks at the previous job timestamp before starting the new job to see if it actually ran.

**Comment by colby** [comment]
:+1:  You da' man.

**Comment by nijotz** [comment]
``` bash
[debug] ffmpeg command line: avconv -y -i 'music/in/Black Dice - Pinball Wizard-lCh4oICt47g.mp4' -vn -acodec libmp3lame -q:a 5 'music/in/Black Dice - Pinball Wizard-lCh4oICt47g.mp3'
Traceback (most recent call last):
  File "/home/nick/.virtualenvs/shitstream/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/nick/.virtualenvs/shitstream/local/lib/python2.7/site-packages/socketio/virtsocket.py", line 403, in _receiver_loop
    retval = pkt_ns.process_packet(pkt)
  File "/home/nick/.virtualenvs/shitstream/local/lib/python2.7/site-packages/socketio/namespace.py", line 155, in process_packet
    return self.process_event(packet)
  File "/home/nick/.virtualenvs/shitstream/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 60, in process_event
    return self.socketio._dispatch_message(app, self, message, args)
  File "/home/nick/.virtualenvs/shitstream/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 135, in _dispatch_message
    ret = self.messages[namespace.ns_name][message](*args)
  File "server.py", line 51, in fn_wrap
    return func(*args, **kwargs)
  File "server.py", line 347, in add_url
    songid = mpdc.addid(uri)
  File "/home/nick/.virtualenvs/shitstream/local/lib/python2.7/site-packages/mpd.py", line 583, in decorator
    return wrapper(self, name, args, bound_decorator(self, returnValue))
  File "/home/nick/.virtualenvs/shitstream/local/lib/python2.7/site-packages/mpd.py", line 229, in _execute
    return retval()
  File "/home/nick/.virtualenvs/shitstream/local/lib/python2.7/site-packages/mpd.py", line 578, in decorator
    return function(self, *args, **kwargs)
  File "/home/nick/.virtualenvs/shitstream/local/lib/python2.7/site-packages/mpd.py", line 357, in _fetch_item
    pairs = list(self._read_pairs())
  File "/home/nick/.virtualenvs/shitstream/local/lib/python2.7/site-packages/mpd.py", line 284, in _read_pairs
    pair = self._read_pair(separator)
  File "/home/nick/.virtualenvs/shitstream/local/lib/python2.7/site-packages/mpd.py", line 275, in _read_pair
    line = self._read_line()
  File "/home/nick/.virtualenvs/shitstream/local/lib/python2.7/site-packages/mpd.py", line 264, in _read_line
    raise CommandError(error)
CommandError: [50@0] {addid} No such song
<Greenlet at 0xad6e5cc: <bound method Socket._receiver_loop of <socketio.virtsocket.Socket object at 0xa8025cc>>> failed with CommandError
```
